# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('colors/*.py', 'colors'),
        ('typography/*.py', 'typography'),
        ('layout/*.py', 'layout'),
        ('spacing/*.py', 'spacing'),
        ('sizing/*.py', 'sizing'),
        ('backgrounds/*.py', 'backgrounds'),
        ('borders/*.py', 'borders'),
        ('effects/*.py', 'effects'),
        ('core/*.py', 'core'),
        ('generators/*.py', 'generators'),
    ],
    hiddenimports=[
        'colors.base',
        'colors.generators',
        'colors.utils',
        'typography.base',
        'layout.base',
        'spacing.base',
        'sizing.base',
        'backgrounds.base',
        'borders.base',
        'effects.base',
        'core.processor',
        'generators.cpp',
        'generators.layout',
        'generators.typography',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'cv2',
        'torch',
        'tensorflow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='mikocss',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
